/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VehicleWindow.java
 *
 * Created on Mar 20, 2011, 12:25:57 PM
 */

package rychlybalik.gui;

import javax.swing.JComboBox;
import javax.swing.SpinnerNumberModel;
import rychlybalik.vehicle.*;

/**
 *
 * @author michal
 */
public class VehicleWindow extends javax.swing.JFrame {

    /** Creates new form VehicleWindow */
    public VehicleWindow() {
        initComponents();
		setVehicle((Vehicle) vehicleType.getItemAt(0));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        Object[] cbo = new Object[4];
        cbo[0] = new Van();
        cbo[1] = new Pickup();
        cbo[2] = new Bicycle();
        cbo[3] = new MHD();
        vehicleType = new javax.swing.JComboBox(cbo);
        speed = new javax.swing.JSpinner();
        payload = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridanie vozidla");

        jLabel2.setText("Typ");

        jLabel3.setText("Rýchlosť");

        jLabel4.setText("Nosnosť");

        submitButton.setText("Pridať");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        vehicleType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(vehicleType, 0, 222, Short.MAX_VALUE)
                    .addComponent(speed, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(payload, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(vehicleType)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(payload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private Integer editingRow;
	void setEditing(int atRow) {
		editingRow = atRow;
		submitButton.setText("Zmeniť");
	}


	private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
		Vehicle v = (Vehicle) vehicleType.getSelectedItem();
		v.setPayload((Integer) payload.getValue());
		v.setSpeed((Integer) speed.getValue());
		if(editingRow == null) {
			MainWindow.addVehicle(v);
		} else {
			MainWindow.editVehicle(editingRow, v);
		}
		this.dispose();
	}//GEN-LAST:event_submitButtonActionPerformed

	private void vehicleTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleTypeActionPerformed
		JComboBox cb = (JComboBox) evt.getSource();
		Vehicle v = (Vehicle) cb.getSelectedItem();

		setVehicle(v);
	}//GEN-LAST:event_vehicleTypeActionPerformed

	public void setVehicle(Vehicle v) {
		int index = 0;
		if(v instanceof Van) index = 0;
		else if(v instanceof Pickup) index = 1;
		else if(v instanceof Bicycle) index = 2;
		else if(v instanceof MHD) index = 3;
		vehicleType.setSelectedIndex(index);

		payload.setModel(new SpinnerNumberModel((int) v.getPayload(), 0, (int) v.getMaxPayload(), 1));
		speed.setValue(v.getSpeed());
	}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner payload;
    private javax.swing.JSpinner speed;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox vehicleType;
    // End of variables declaration//GEN-END:variables




}
