/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PotvrdOdeberVuz.java
 *
 * Created on 14.3.2011, 16:55:43
 */

package rychlybalik.GUI;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Vojta
 */
public class PotvrdOdeberZasilku extends javax.swing.JFrame {

    RychlyBalik hlavni;
    int radek;

    /** Creates new form PotvrdOdeberVuz */
    public PotvrdOdeberZasilku(RychlyBalik hlavni,int radek) {
        this.hlavni=hlavni;
        this.radek=radek;

        setSize(200,100);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize(); //velikost okna
        setLocation(((d.width - getSize().width) / 2), ((d.height - getSize().height) / 2));
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(145, 171, 210));
        setMinimumSize(new java.awt.Dimension(200, 100));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(145, 171, 210));
        jPanel1.setFocusable(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(145, 171, 210));
        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Odvolat označené doručování?");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jButton1.setBackground(new java.awt.Color(145, 171, 230));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
      hlavni.sezZas.getSeznamZasilek().get(radek).getProstredek().setExpeding(false);
      hlavni.sezZas.getSeznamZasilek().get(radek).getDopravator().setExpeding(false);
      hlavni.sezZas.odeberZasilku(radek);
      hlavni.refreshSeznamuZasilek();
      hlavni.refreshVozovehoParku();
      hlavni.refreshSeznamuPracovniku();
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PotvrdOdeberVuz().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
