/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VuzPridani.java
 *
 * Created on 7.3.2011, 10:50:12
 */
package rychlybalik.GUI;

import java.awt.*;
import java.io.IOException;
import rychlybalik.TypDopravy.*;
import rychlybalik.VozovyPark.*;

/**
 *
 * @author Vojta
 */
public class VuzPridani extends javax.swing.JFrame {

    protected double nosnost;
    protected double rychlost;
    protected int stavbuttonu = 5;
    SpolecneAtributy k;
    /*HlavniOkno*/
    RychlyBalik parent;

    /** Creates new form VuzPridani */
    public VuzPridani(RychlyBalik neco1) {

        this.parent = neco1;
        setSize(300, 300);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize(); //velikost okna
        setLocation(((d.width - getSize().width) / 2), ((d.height - getSize().height) / 2));

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radio_dodavka = new javax.swing.JRadioButton();
        radio_pickup = new javax.swing.JRadioButton();
        radio_kolo = new javax.swing.JRadioButton();
        radio_MHD = new javax.swing.JRadioButton();
        NazevTypDopravy = new javax.swing.JTextField();
        NazevNosnost = new javax.swing.JTextField();
        zadaniNosnosti = new javax.swing.JTextField();
        NazevRychlost = new javax.swing.JTextField();
        zadaniRychlosti = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(145, 171, 210));

        radio_dodavka.setBackground(new java.awt.Color(145, 171, 210));
        buttonGroup1.add(radio_dodavka);
        radio_dodavka.setText("Dodávka");
        radio_dodavka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_dodavkaActionPerformed(evt);
            }
        });

        radio_pickup.setBackground(new java.awt.Color(145, 171, 210));
        buttonGroup1.add(radio_pickup);
        radio_pickup.setText("Pick-up");
        radio_pickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_pickupActionPerformed(evt);
            }
        });

        radio_kolo.setBackground(new java.awt.Color(145, 171, 210));
        buttonGroup1.add(radio_kolo);
        radio_kolo.setText("Kolo");
        radio_kolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_koloActionPerformed(evt);
            }
        });

        radio_MHD.setBackground(new java.awt.Color(145, 171, 210));
        buttonGroup1.add(radio_MHD);
        radio_MHD.setText("MHD");
        radio_MHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_MHDActionPerformed(evt);
            }
        });

        NazevTypDopravy.setBackground(new java.awt.Color(145, 171, 210));
        NazevTypDopravy.setEditable(false);
        NazevTypDopravy.setFont(new java.awt.Font("Tahoma", 1, 11));
        NazevTypDopravy.setForeground(new java.awt.Color(255, 255, 255));
        NazevTypDopravy.setText("Typ Dopravy");
        NazevTypDopravy.setBorder(null);

        NazevNosnost.setBackground(new java.awt.Color(145, 171, 210));
        NazevNosnost.setEditable(false);
        NazevNosnost.setForeground(new java.awt.Color(255, 255, 255));
        NazevNosnost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NazevNosnost.setText("Nosnost");
        NazevNosnost.setBorder(null);

        zadaniNosnosti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        NazevRychlost.setBackground(new java.awt.Color(145, 171, 210));
        NazevRychlost.setEditable(false);
        NazevRychlost.setForeground(new java.awt.Color(255, 255, 255));
        NazevRychlost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NazevRychlost.setText("Rychlost");
        NazevRychlost.setBorder(null);

        zadaniRychlosti.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jButton1.setBackground(new java.awt.Color(145, 171, 230));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Přidej");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_dodavka)
                    .addComponent(radio_pickup)
                    .addComponent(NazevTypDopravy, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_kolo)
                    .addComponent(radio_MHD))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NazevRychlost, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NazevNosnost, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zadaniNosnosti, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zadaniRychlosti, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NazevTypDopravy, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_dodavka)
                            .addComponent(zadaniNosnosti, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NazevNosnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radio_pickup)
                        .addGap(3, 3, 3)
                        .addComponent(radio_kolo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_MHD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(NazevRychlost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zadaniRychlosti, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_MHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_MHDActionPerformed
        // TODO add your handling code here:zadaniNosnosti.disable();
        zadaniNosnosti.enable();
        zadaniRychlosti.disable();
        zadaniRychlosti.setBackground(Color.gray);
        zadaniNosnosti.setBackground(Color.white);
        stavbuttonu = 3;
    }//GEN-LAST:event_radio_MHDActionPerformed

    private void radio_dodavkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_dodavkaActionPerformed
        zadaniNosnosti.disable();
        zadaniRychlosti.disable();
        zadaniRychlosti.setBackground(Color.gray);
        zadaniNosnosti.setBackground(Color.gray);
        stavbuttonu = 0;
    }//GEN-LAST:event_radio_dodavkaActionPerformed

    private void radio_pickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_pickupActionPerformed
        zadaniNosnosti.enable();
        zadaniRychlosti.disable();
        zadaniRychlosti.setBackground(Color.gray);
        zadaniNosnosti.setBackground(Color.white);
        stavbuttonu = 1;
    }//GEN-LAST:event_radio_pickupActionPerformed

    private void radio_koloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_koloActionPerformed
        zadaniNosnosti.enable();
        zadaniRychlosti.enable();
        zadaniRychlosti.setBackground(Color.white);
        zadaniNosnosti.setBackground(Color.white);
        stavbuttonu = 2;
    }//GEN-LAST:event_radio_koloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VozovyPark park = new VozovyPark();
        park = parent.getVozPark();
        


        switch (stavbuttonu) {
            case 0:
                k = new DodavkaVelka();


                park.pridejVuz(k);
                parent.setVozPark(park);
                parent.getOdeberVuz().setEnabled(true);
                parent.getEditujProstredek().setEnabled(true);


                break;//(Double.valueOf(zadaniNosnosti.getText()));

            case 1:

                try {
                    Double.valueOf(zadaniNosnosti.getText());
                } catch (java.lang.NumberFormatException e) {
                    WarningVstup okynko = new WarningVstup(this, "Nosnost musí být větší než 0,\nmaximální nosnost je 2500 (kg)!");
                    okynko.setVisible(true);
                    dispose();
                }
                nosnost = Double.valueOf(zadaniNosnosti.getText());
                if (nosnost <= 2500 && nosnost > 0) {
                    k = new PickUp(Double.valueOf(zadaniNosnosti.getText()));
                    park.pridejVuz(k);
                    parent.setVozPark(park);
                    parent.getOdeberVuz().setEnabled(true);
                    parent.getEditujProstredek().setEnabled(true);
                } else {
                    WarningVstup okynko = new WarningVstup(this, "Nosnost musí být větší než 0,\nmaximální nosnost je 2500 (kg)!");
                    okynko.setVisible(true);
                    dispose();
                }


                break;//
            case 2:

                try {
                    Double.valueOf(zadaniNosnosti.getText());
                    Double.valueOf(zadaniRychlosti.getText());
                } catch (java.lang.NumberFormatException e) {
                    WarningVstup okynko = new WarningVstup(this, "Nosnost musí být z interv. (0,10>.\nRychlost musí být z inter. (0,100>.");
                    okynko.setVisible(true);
                    dispose();
                }

                nosnost = Double.valueOf(zadaniNosnosti.getText());
                rychlost = Double.valueOf(zadaniRychlosti.getText());
                if ((nosnost <= 10 && nosnost > 0) && (rychlost <= 100 && rychlost > 0)) {
                    k = new Kolo(Double.valueOf(zadaniNosnosti.getText()), Double.valueOf(zadaniRychlosti.getText()));
                    park.pridejVuz(k);
                    parent.setVozPark(park);
                    parent.getOdeberVuz().setEnabled(true);
                    parent.getEditujProstredek().setEnabled(true);
                } else {
                    WarningVstup okynko = new WarningVstup(this, "Nosnost musí být z interv. (0,10>.\nRychlost musí být z inter. (0,100>.");
                    okynko.setVisible(true);
                    dispose();
                }



                break;
            case 3:
                try {
                    Double.valueOf(zadaniNosnosti.getText());
                } catch (java.lang.NumberFormatException e) {
                    WarningVstup okynko = new WarningVstup(this, "Nosnost musí být větší než 0,\nmaximální nosnost je 15 (kg)!");
                    okynko.setVisible(true);
                    dispose();
                }
                nosnost = Double.valueOf(zadaniNosnosti.getText());
                if (nosnost <= 15 && nosnost > 0) {
                    k = new MHD(Double.valueOf(zadaniNosnosti.getText()));
                    park.pridejVuz(k);
                    parent.setVozPark(park);
                    parent.getOdeberVuz().setEnabled(true);
                    parent.getEditujProstredek().setEnabled(true);
                } else {
                    WarningVstup okynko = new WarningVstup(this, "Nosnost musí být větší než 0,\nmaximální nosnost je 15 (kg)!");
                    okynko.setVisible(true);
                    dispose();
                }
                break;
            default:
                WarningVstup okynko = new WarningVstup(this, "Nevybral jsi typ dopravy!!");
                    okynko.setVisible(true);
                    dispose();
                dispose();
                break;//
        }


        parent.refreshVozovehoParku();
        
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new VuzPridani(vozPark).setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NazevNosnost;
    private javax.swing.JTextField NazevRychlost;
    private javax.swing.JTextField NazevTypDopravy;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radio_MHD;
    private javax.swing.JRadioButton radio_dodavka;
    private javax.swing.JRadioButton radio_kolo;
    private javax.swing.JRadioButton radio_pickup;
    private javax.swing.JTextField zadaniNosnosti;
    private javax.swing.JTextField zadaniRychlosti;
    // End of variables declaration//GEN-END:variables
}
