/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PotvrdOdeberVuz.java
 *
 * Created on 14.3.2011, 16:55:43
 */

package rychlybalik.GUI;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Vojta
 */
public class WarningVstup extends javax.swing.JFrame {

    VuzPridani hlavni;
    VuzEdit hlavni2;
    PracovnikPridani hlavni3;
    PracovnikEdit hlavni4;
    RychlyBalik hlavni5;
    String text;

    /** Creates new form PotvrdOdeberVuz */
    public WarningVstup(RychlyBalik hlavni,String text) {
        this.hlavni5=hlavni;
        this.text=text;
        setTitle("VAROVÁNÍ");


        setSize(200,100);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize(); //velikost okna
        setLocation(((d.width - getSize().width) / 2), ((d.height - getSize().height) / 2));
        initComponents();
    }

    public WarningVstup(VuzPridani hlavni,String text) {
        this.hlavni=hlavni;
        this.text=text;
        setTitle("VAROVÁNÍ");
        

        setSize(200,100);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize(); //velikost okna
        setLocation(((d.width - getSize().width) / 2), ((d.height - getSize().height) / 2));
        initComponents();
    }

    public WarningVstup(PracovnikPridani hlavni3,String text) {
        this.hlavni3=hlavni3;
        this.text=text;
        setTitle("VAROVÁNÍ");


        setSize(200,100);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize(); //velikost okna
        setLocation(((d.width - getSize().width) / 2), ((d.height - getSize().height) / 2));
        initComponents();
    }

    public WarningVstup(PracovnikEdit hlavni4,String text) {
        this.hlavni4=hlavni4;
        this.text=text;
        setTitle("VAROVÁNÍ");


        setSize(200,100);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize(); //velikost okna
        setLocation(((d.width - getSize().width) / 2), ((d.height - getSize().height) / 2));
        initComponents();
    }

    public WarningVstup(VuzEdit hlavni,String text) {
        this.hlavni2=hlavni;
        this.text=text;
        setTitle("VAROVÁNÍ");


        setSize(200,100);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize(); //velikost okna
        setLocation(((d.width - getSize().width) / 2), ((d.height - getSize().height) / 2));
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(145, 171, 210));
        setMinimumSize(new java.awt.Dimension(200, 130));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(145, 171, 210));
        jPanel1.setFocusable(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(145, 171, 210));
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 0));
        jTextArea1.setText(text);
        jTextArea1.setAlignmentX(CENTER_ALIGNMENT);
        jTextArea1.setAlignmentY(CENTER_ALIGNMENT);
        jTextArea1.setBorder(null);
        
        jPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        jButton1.setBackground(new java.awt.Color(145, 171, 230));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>



    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        dispose();
    }

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PotvrdOdeberVuz().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration

}