/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Apr 10, 2011, 12:31:36 PM
 */

package rss;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author michal
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    public MainWindow() throws SQLException {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        manageSourceButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        link = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new SourcesTable();
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                tableUpdateText();
            }
        });
        jComboBox1 = new SourcesComboBox( (SourcesTable) jTable1);
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RSS");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setText("Refresh");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        manageSourceButton.setText("Manage source");
        manageSourceButton.setEnabled(false);
        manageSourceButton.setFocusable(false);
        manageSourceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        manageSourceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        manageSourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSourceButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(manageSourceButton);

        jButton3.setText("Add source");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(title, java.awt.BorderLayout.PAGE_START);

        description.setColumns(20);
        description.setEditable(false);
        description.setLineWrap(true);
        description.setRows(5);
        jScrollPane2.setViewportView(description);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        link.setForeground(new java.awt.Color(0, 0, 255));
        link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkMouseClicked(evt);
            }
        });
        jPanel1.add(link, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, java.awt.BorderLayout.NORTH);

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);
        getContentPane().add(status, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void linkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMouseClicked
		try {
			try {
				Desktop.getDesktop().browse(new URI(link.getText()));
			} catch (IOException ex) {
				Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
			}
		} catch (URISyntaxException ex) {
			Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
		}
	}//GEN-LAST:event_linkMouseClicked

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
		JComboBox cb = (JComboBox) evt.getSource();
        Object item = cb.getSelectedItem();

		if(item instanceof Source) {
			try {
				((SourcesTable) jTable1).setSource( ((Source) item).getId() );
			} catch (SQLException ex) {
				Logger.getLogger(SourcesComboBox.class.getName()).log(Level.SEVERE, null, ex);
			}
			manageSourceButton.setEnabled(true);
		} else {
			manageSourceButton.setEnabled(false);
			try {
				((SourcesTable) jTable1).setSource(null);
			} catch (SQLException ex) {
				Logger.getLogger(SourcesComboBox.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}//GEN-LAST:event_jComboBox1ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		SourceWindow sourceWindow = new SourceWindow();
		sourceWindow.setComboBox(jComboBox1);
		sourceWindow.setVisible(true);

	}//GEN-LAST:event_jButton3ActionPerformed

	private void manageSourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSourceButtonActionPerformed
		Source src = (Source) jComboBox1.getSelectedItem();
		SourceWindow sourceWindow = new SourceWindow();
		sourceWindow.setComboBox(jComboBox1);
		sourceWindow.setSource(src);
		sourceWindow.setVisible(true);
	}//GEN-LAST:event_manageSourceButtonActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// load all sources
		Object o;
		ArrayList<Post> al;
		Connection conn;
		PreparedStatement st = null;
		try {
			conn = Main.getConnection();

			st = conn.prepareStatement("INSERT INTO posts (title, link, description, pubdate, source_id) "
					+ "VALUES (?,?,?,?,?)");
		} catch(SQLException e) {
			System.err.println(e);
		}


		for(int i = 0; i <= jComboBox1.getModel().getSize(); i++) {
			o = jComboBox1.getModel().getElementAt(i);
			if(o instanceof Source) {
				RSSFeedParser rfp = new RSSFeedParser( ((Source) o).getUrl() );
				al = rfp.readFeed();
				for(Post post : al)  {
					System.out.println("adding "+post.getTitle());
					try {
						st.setString(1, post.getTitle());
						st.setString(2, post.getLink());
						st.setString(3, post.getDescription());
						st.setDate(4, new java.sql.Date(post.getDate().getTime()));
						st.setInt(5, ((Source) o).getId());

						st.addBatch();
						st.executeBatch();
					} catch(SQLException e) {}
				}
			}
		}
		
		try {
			st.close();
		} catch (SQLException ex) {
			Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
		}
	}//GEN-LAST:event_jButton1ActionPerformed

	private void tableUpdateText() {
		if(jTable1.getSelectedRow() == -1) {
			return;
		}
		System.out.println(""+jTable1.getSelectedRow());
		Post row = ((SourcesTable.SourcesTableModel) jTable1.getModel()).getPosts().get(
			jTable1.getSelectedRow()
		);

		title.setText(row.getTitle());
		description.setText(row.getDescription());
		link.setText(row.getLink());
	}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea description;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel link;
    private javax.swing.JButton manageSourceButton;
    private javax.swing.JLabel status;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
