/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsWindow.java
 *
 * Created on May 14, 2011, 2:04:38 PM
 */

package pexeso;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author michal
 */
public class SettingsWindow extends javax.swing.JFrame {

    /** Creates new form SettingsWindow */
    public SettingsWindow() {
        initComponents();
		setLocationRelativeTo(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cols = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rows = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        theme = new javax.swing.JComboBox();
        comp = new javax.swing.JComboBox();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nastavenia");
        setResizable(false);

        jLabel1.setText("<html><b>Veľkosť hracej plochy</b></html>");

        cols.setModel(new javax.swing.SpinnerNumberModel(MainWindow.getInstance().getTiles().getTileCols(), 2, 8, 1));

        jLabel2.setLabelFor(cols);
        jLabel2.setText("Stĺpcov:");

        jLabel3.setLabelFor(rows);
        jLabel3.setText("Riadkov:");

        rows.setModel(new javax.swing.SpinnerNumberModel(MainWindow.getInstance().getTiles().getTileRows(), 2, 8, 1));

        jLabel4.setLabelFor(theme);
        jLabel4.setText("Použité obrázky:");

        jLabel5.setLabelFor(comp);
        jLabel5.setText("Obtiažnosť počítača:");

        theme.setModel(getThemeComboBoxModel());

        comp.setModel(getCompComboBoxModel());
        comp.setSelectedIndex(getCompDifficulty());

        save.setText("Nastaviť");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(theme, 0, 242, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(comp, 0, 242, Short.MAX_VALUE)
                    .addComponent(save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(rows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(theme, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
		TileMap tiles = MainWindow.getInstance().getTiles();
		try {
			tiles.setTileSize((Integer) rows.getValue(), (Integer) cols.getValue());
			tiles.setTheme((String) theme.getSelectedItem());
			System.out.println(""+comp.getSelectedIndex());
			switch(comp.getSelectedIndex()) {
				case 0:
					tiles.setCompDifficulty(Computer.EASY);
					break;
				case 1:
					tiles.setCompDifficulty(Computer.MEDIUM);
					break;
				case 2:
					tiles.setCompDifficulty(Computer.HARD);
					break;
				case 3:
					tiles.setCompDifficulty(Computer.INSANE);
					break;
			};

			this.dispose();
			MainWindow.getInstance().newGame();
		} catch (PexesoException ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}//GEN-LAST:event_saveActionPerformed

	private ComboBoxModel getThemeComboBoxModel() {
		Object[] items = MainWindow.getInstance().getTiles().getThemes().toArray();
		return new DefaultComboBoxModel(items);
	}

	private ComboBoxModel getCompComboBoxModel() {
		String[] items = {"Ľahký", "Stredne ťažký", "Ťažký", "Šialený"};
		return new DefaultComboBoxModel(items);
	}

	private int getCompDifficulty() {
		switch(MainWindow.getInstance().getTiles().getCompDifficulty()) {
			case Computer.EASY:
				return 0;
			case Computer.MEDIUM:
				return 1;
			case Computer.HARD:
				return 2;
			case Computer.INSANE:
				return 3;
		};
		return 1;
	}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cols;
    private javax.swing.JComboBox comp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner rows;
    private javax.swing.JButton save;
    private javax.swing.JComboBox theme;
    // End of variables declaration//GEN-END:variables

}
