
package view;

import java.awt.Dimension;

/**
 *
 * @author  Miroslav Balík
 */
public class MainFrame extends javax.swing.JFrame {
    /** plocha na kresleni
     */
    public KresliciPlocha plocha = new KresliciPlocha();
    
    /** Konstruktor. Nastavi komponenty pomoci generovaneho kodu
     *a pote nahradi tlacitko nasi plochou, ktera ma pretizenou metodu pro vykreslovani - 
     *metodu paint
     */
    public MainFrame() {
        initComponents();
        jPanelProKresleni.add(plocha);  
        plocha.setPreferredSize(new Dimension(400,400));
        plocha.repaint();
        pack();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProKresleni = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonKonec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelProKresleni.setLayout(new java.awt.BorderLayout());

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obr/obdelnik.gif"))); // NOI18N
        jToggleButton1.setText("jToggleButton1");
        jPanelProKresleni.add(jToggleButton1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelProKresleni, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButtonKonec.setText("Konec");
        jButtonKonec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKonecActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKonec, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKonecActionPerformed
        System.exit(2);
    }//GEN-LAST:event_jButtonKonecActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKonec;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelProKresleni;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
    
}
